name: Release

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Checkout
      uses: actions/checkout@v2

    - name: Build
      run: docker build -t reecerussell/migrations .

    - name: Integration Tests
      workingDirectory: test
      run: docker-compose up --build --exit-code-from tests

    - name: Codecov
      uses: codecov/codecov-action@v1.0.15
      with:
        file: test/output/coverage.out

    - name: Publish Docker Image
      run: |
        docker login --username ${{ secrets.DOCKER_USERNAME }} --password ${{ secrets.DOCKER_TOKEN }}
        docker push reecerussell/migrations