name: Release

on:
  push:
    branches: [ master ]
  pull_request:

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Build
        run: docker build -t reecerussell/migrations .

      - name: Save
        if: github.ref == 'refs/heads/master' && github.event_name == 'push'
        run: docker save reecerussell/migrations:latest > migrations.tar

      - name: Archive
        uses: actions/upload-artifact@v2
        if: github.ref == 'refs/heads/master' && github.event_name == 'push'
        with:
          name: docker-image
          path: migrations.tar

  test:
    name: Test
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Integration Tests
        working-directory: test
        run: docker-compose up --build --exit-code-from tests

      - name: Archive Coverage
        uses: actions/upload-artifact@v2
        if: github.ref == 'refs/heads/master' && github.event_name == 'push'
        with:
          name: coverage
          path: test/output/coverage.out
    
  coverage:
    name: Upload Test Coverage
    runs-on: ubuntu-latest
    needs: test
    if: github.ref == 'refs/heads/master' && github.event_name == 'push'
    steps:
      - name: Download Report
        uses: actions/download-artifact@v2
        with:
          name: coverage
          path: coverage.out

      - name: ls
        run: ls

      - name: Submit Report
        uses: codecov/codecov-action@v1.0.15
        with:
          file: migrations/coverage.out

  publish:
    name: Publish Docker Image
    runs-on: ubuntu-latest
    needs: test
    if: github.ref == 'refs/heads/master' && github.event_name == 'push'
    steps:
      - name: Download Archive
        uses: actions/download-artifact@v2
        with:
          name: docker-image
          path: migrations.tar

      - name: ls
        run: ls

      - name: Load Image
        run: docker load < migrations.tar

      - name: Push Image
        run: |
          docker login --username ${{ secrets.DOCKER_USERNAME }} --password ${{ secrets.DOCKER_TOKEN }}
          docker push reecerussell/migrations

  release:
    name: Release
    runs-on: ubuntu-latest
    needs: test
    if: github.ref == 'refs/heads/master' && github.event_name == 'push'
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Create Release
        shell: bash
        run: |
          chmod +x ./scripts/build_release.sh
          ./scripts/build_release.sh
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          VERBOSE: 1
